# Generated by Django 4.0.6 on 2023-04-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Alternativa',
        ),
    ]
