# Generated by Django 4.0.6 on 2023-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_rename_choice_alternativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='pub_data',
            new_name='data_pub',
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='alternativa_text',
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='votos',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='pergunta_text',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='quant_votos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de votos'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='enunciado',
            field=models.CharField(default='', max_length=150),
        ),
    ]
