# Generated by Django 4.0.6 on 2023-07-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_interno', '0002_autor_leitor_remove_comentario_autor_noticia_edicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jornal_interno.noticia'),
        ),
    ]
